### ISSUE TITLE
Import doesn't work

### ISSUE THREAD

**Issue by AndyGFX** [UnityCommunity/TiledUtilities#1]
Hi,

I tried reimport your example to new gameObject and I got this error:

KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[System.UInt32,UnityEngine.Sprite].get_Item (UInt32 key) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:595)
SpriteCache.GetSprite (UInt32 gid) (at Assets/Unity Asset LIBS/CubesTeam Common/Scripts/TiledUtilities/Editor/SpriteCache.cs:54)
TiledMapEditor.CreateSpritesForLayer (.SpriteCache spriteCache, UnityEngine.GameObject layerObject, Tiled.TileLayer tileLayer) (at Assets/Unity Asset LIBS/CubesTeam Common/Scripts/TiledUtilities/Editor/TiledMapEditor.cs:85)
TiledMapEditor.OnInspectorGUI () (at Assets/Unity Asset LIBS/CubesTeam Common/Scripts/TiledUtilities/Editor/TiledMapEditor.cs:52)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean forceDirty, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect, Boolean eyeDropperDirty) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1211)
UnityEditor.DockArea:OnGUI()

**Comment by AndyGFX** [comment]
Here is quick fix.
 
to SpriteCashe.cs add this method:

    public string MakeRelativeToUnityProject(string toPath)
    {
        string fullPath = toPath;
        string assetPath = Application.dataPath;
        assetPath = assetPath.Replace("/", "\\");
        string relativePath = "Assets" + fullPath.ToString().Replace(assetPath, "");

        return relativePath;
    }

end replace all asset loadings to:

var sprites = AssetDatabase.LoadAllAssetsAtPath(this.MakeRelativeToUnityProject(info.assetPath))
                                       .OfType<Sprite>()
                                       .ToArray();


AndyGFX.

**Comment by nickgravelyn** [comment]
I'm not sure how that's different than the existing [TiledHelpers.GetAssetPath](https://github.com/UnityCommunity/TiledUtilities/blob/master/Editor/TiledHelpers.cs#L6) method which is used to configure the path in [SpriteCache on line 19](https://github.com/UnityCommunity/TiledUtilities/blob/master/Editor/SpriteCache.cs#L19). Have you determined the key difference between the code you've posted and the original code?

**Comment by AndyGFX** [comment]
Hi,

Before error line a had warning, that asset has wrong path and is not relative to asset.

Your method make only slash changes if first is /, but under Windows is first drive ID.

Andy.

**Comment by nickgravelyn** [comment]
I can see how the file path would have backslashes, and thus the attempt to remove the dataPath didn't work. I just made a change to the TiledHelper method in c84cde5 that I think will fix this. Let me know if that works without you having to add your own method around that.

**Comment by AndyGFX** [comment]
Hi,
yes works now.

thx.
